# Generated by Django 4.1.1 on 2022-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percentDiscount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
            preserve_default=False,
        ),
    ]
